new: ignore empty fields
pamburus/hl pull request #3
Opened 2020-12-31 08:45 UTC by qqshfox

2021-01-03 19:58 UTC, pamburus commented
Thank you for your pull request!

But I would like not to hide empty fields by default and even without a configuration option.
It may be significant to distinguish between empty field or missing field.

Please add command-line flags for it `--hide-empty-fields` (and optionally `--show-empty-fields` to undo `--hide-empty-fields`).
If you want it by default, add an alias to the `hl` command with `--hide-empty-fields` in your environment.

2021-01-03 19:59 UTC, pamburus requested changes
Please add configuration option and keep current behavior by default.

2021-01-05 03:38 UTC, qqshfox commented
> Thank you for your pull request!
> 
> But I would like not to hide empty fields by default and even without a configuration option.
> It may be significant to distinguish between empty field or missing field.
> 
> Please add command-line flags for it `--hide-empty-fields` (and optionally `--show-empty-fields` to undo `--hide-empty-fields`).
> If you want it by default, add an alias to the `hl` command with `--hide-empty-fields` in your environment.

@pamburus Thanks for the review. New flag added.

2021-01-06 18:00 UTC, pamburus requested changes

2021-01-06 18:00 UTC, pamburus commented on src/main.rs
> +    /// Show empty fields, overrides --hide_empty_fields option.
`structopt` automatically replaces underscores with hyphens for option names.
But it does not replace them in comments.
So, please use correct style in comments (which are automatically converted to option descriptions).
Replace `--hide_empty_fields` -> `--hide-empty-fields`

2021-01-06 18:00 UTC, pamburus commented on src/main.rs
> +    /// Hide empty fields, only applys for null, string, object and array fields.
Replace `only applys for null, string, object and array fields.` -> `applies for null, string, object and array fields only.`

2021-01-07 07:54 UTC, pamburus approved these changes

2021-01-07 07:55 UTC, merged